version: "3.9"

services:
  db:
    image: postgres:16
    container_name: fiber-v3-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fiber
    ports:
      - "5450:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: